FROM node:25-alpine3.21 AS build 

WORKDIR /app
COPY package*.json ./   

RUN npm install 
COPY . .    

RUN npm run build 


FROM nginx:1.29.3   
COPY --from=build /app/dist /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]